version: "3.3"

services:
  loadbalancer:
    image: traefik:latest
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8081:8081"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  webmap:
    image: webmap
    build:
      context: ./webmap
    depends_on:
      - loadbalancer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webmap.rule=Host(`localhost`) || Host(`ec2-3-105-15-240.ap-southeast-2.compute.amazonaws.com`)"
      - "traefik.http.services.webmap.loadbalancer.server.port=3000"
      - "traefik.http.routers.webmap.entrypoints=web"

  backend:
    image: rio-tiler
    depends_on:
      - loadbalancer
    env_file:
      - .env
    environment:
      ZARR_STORE: s3://imos-data-pixeldrill/vhnguyen/playground/multi-years/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`rio.localhost`) || (Host(`ec2-3-105-15-240.ap-southeast-2.compute.amazonaws.com`) && PathPrefix(`/tiles`)) || (Host(`ec2-3-105-15-240.ap-southeast-2.compute.amazonaws.com`) && Path(`/hello`)) || (Host(`ec2-3-105-15-240.ap-southeast-2.compute.amazonaws.com`) && PathPrefix(`/tilejson.json`)) || (Host(`ec2-3-105-15-240.ap-southeast-2.compute.amazonaws.com`) && PathPrefix(`/time_range`))"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      - "traefik.http.routers.backend.entrypoints=web"
    build:
      context: ./
    restart: unless-stopped
